name: Build

on:
    push:
        branches: [ main, stable, dev ]

env:
    CARGO_TERM_COLOR: always
    ARTIFACT_NAME: ciphergen-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_attempt }}
    CACHE_PATHS: |
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
        target/

jobs:
    check:
        name: Check
        uses: ./.github/workflows/check.yml
    build:
        name: Build ${{ matrix.platform.name }}
        runs-on: ${{ matrix.platform.os }}
        needs: check
        strategy:
            matrix:
                platform:
                    - name: Linux AMD64
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - name: Linux AARCH64
                      os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                    - name: Windows AMD64
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
        steps:
            - name: Cache
              uses: actions/cache@v3
              with:
                  path: ${{ env.CACHE_PATHS }}
                  key: build-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
            - name: Checkout
              uses: actions/checkout@v3
            - name: Add Target
              run: rustup target add ${{ matrix.platform.target }}
            - name: Build
              run: cargo build --target ${{ matrix.platform.target }}
            - uses: actions/upload-artifact@v3
              with:
                  name: ${{ env.ARTIFACT_NAME }}
                  path: target/
