name: Check

on: [ push, pull_request, workflow_call ]

env:
  CARGO_TERM_COLOR: always
  CACHE_PATHS: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_PATHS }}
          key: check-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check
        run: cargo check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_PATHS }}
          key: test-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: cargo test
