name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: [ check, test ]
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ciphergen-linux-x86_64-${{ github.SHA }}
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ciphergen-windows-x86_64-${{ github.SHA }}
      - name: List Local Files
        run: tree -a .
      - name: Create Binary Distributions
        run: |
          zip -jr ciphergen-linux-x86_64.zip x86_64-unknown-linux-gnu/release/ciphergen README.md LICENSE
          zip -jr ciphergen-windows-x86_64.zip x86_64-pc-windows-msvc/release/ciphergen.exe README.md LICENSE
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.REPOSITORY }}
          TAG: ${{ github.REF_NAME }}
        run: |
          gh release create $TAG \
            "ciphergen-linux-x86_64.zip#Linux-x86_64.zip" \
            "ciphergen-windows-x86_64.zip#Windows-x86_64.zip" \
            --title "${TAG#v}" \
            --notes "$(git tag -l --format '%(contents:subject)%0a%0a%(contents:body)' $TAG | echo)" \
            --verify-tag \
            --latest
