name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: [ check, test ]
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ciphergen-linux-x86_64-${{ github.SHA }}
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ciphergen-windows-x86_64-${{ github.SHA }}
      - name: List Local Files
        run: tree -a .
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.REPOSITORY }}
          TAG: ${{ github.REF_NAME }}
        run: |
          gh release create $TAG \
            "ciphergen-linux-x86_64-${{ github.SHA }}*#Linux (x86_64)" \
            "ciphergen-windows-x86_64-${{ github.SHA }}*#Windows (x86_64)" \
            "README.md" \
            "LICENSE" \
            --repo $REPOSITORY \
            --title "${TAG#v}" \
            --generate-notes \
            --verify-tag \
            --latest
